-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

profiles['junk'] = S{
	'Acheron Shield',
	'Acorn',
	'Adaman Ore',
	'Adamantoise Shell',
	'Adoulinian Kelp',
	'Aht Urhgan Brass',
	'Akaso',
	'Antlion Jaw',
	'Arrowwood Log',
	'Ash Log',
	'Auric Sand',
	'Barnacle',
	'Bastore Bream',
	'Bat Fang',
	'Bay Leaves',
	'Beehive Chip',
	'Beetle Jaw',
	'Bhefhel Marlin',
	'Bird Egg',
	'Bismuth Ore',
	'Black Eel',
	'Black Ghost',
	'Black Pepper',
	'Black Prawn',
	'Black Sole',
	'Blk. Tiger Fang',
	'Bloodblotch',
	'Blue Peas',
	'Bluetail',
	'Bugard Tusk',
	'Burdock',
	'Bone Chip',
	'Brass Loach',
	'Ca Cuong',
	'Cactus Stems', 
	'Carrier Crab Carapace',
	'Chapuli Horn',
	'Chapuli Wing',
	'Chestnut',
	'Chestnut Log',
	'Cobalt Jellyfish',
	'Colibri Beak',
	'Cone Calamary',
	'Contortopus',
	'Copper Frog',
	'Copper Ore',
	'Coral Fungus',
	'Craklaw Pincer',
	'Crab Shell',
	'Crawler Cocoon',
	'Crawler Egg',
	'Crayfish',
	'Crescent Fish',
	'Dark Bass',
	'Dst. Nugget',
	'Darksteel Ore',
	'Deathball',
	'Divine Log',
	'Dogwood Log',
	'Dragon Bone',
	'Dragon Fruit',
	'Dragon Talon',
	'Dragonfish',
	'Dryad Root',
	'Dwarf Remora',
	'Ebony Log',
	'Eggplant',
	'Elixir Vitae',
	'Elm Log',
	'Elshimo Newt',
	'El. Pachira Fruit',
	'Emperor Fish',
	'Ether',
	'Faerie Apple',
	'Felicifruit',
	'Fish Bones',
	'Flax Flower',
	'Flint Stone',
	'Flytrap Leaf',
	'Fresh Marjoram',
	'Fresh Mugwort',
	'Gavial Fish',
	'Giant Catfish',
	'Gigant Squid',
	'Giant Stinger',
	'Gold Carp',
	'Grain Seeds',
	'Green Rock',
	'Grimmonite',
	'Grove Cuttings',
	'Guatambu Log',
	'Gugru Tuna',
	'Habaneros',
	'Hare Meat',
	'H.Q. Crab Shell',
	'H.Q. Scp. Shell',
	'Honey',
	'Igneous Rock',
	'Infinity Core',
	'Insect Wing',
	'Iron Ore',
	'Isleracea',
	'Kapor Log',
	'Kazham Peppers',
	'Khroma Ore',
	'King Locust',
	'Kopparnickel Ore',
	'Kukuru Bean',
	'La Theine Cbg.',
	'Lacquer Tree Log',
	'Land Crab Meat',
	'Lesser Chigoe',
	'Little Worm',
	'Loc. Elutriator',
	'Mackerel',
	'Mahogany Log',
	'Maple Log',
	'Matamata Shell',
	'Marguerite',
	'Matsya',
	'Meteorite',
	'Mhaura Garlic',
	'Millioncorn',
	'Moko Grass',
	'Moorish Idol',
	'Mushroom Locust',
	'Mythril Ore',
	'Napa',
	'Nopales',
	'Oak Log',
	'Orichalcum Ore',
	'Pamamas',
	'Pebble',
	'Peiste Skin',
	'Persikos',
	'Phrygian Ore',
	'Pine Nuts',
	'Pipira',
	'Poison Flour',
	'Potion',
	'Puffball',
	'Pugil Scales',
	'Pumpkin Pie',
	'Quus',
	'Raaz Hide',
	'Raaz Tusk',
	'Rabbit Hide',
	'Ram Horn',
	'Raptor Skin',
	'Red Moko Grass',
	'Red Rose',
	'Red Terrapin',
	'Rolanberry',
	'Ronfaure Chestnut',
	'Ruddy Seema',
	'Rusty Bucket',
	'Rye Flour',
	'Sage',
	'San d\'Or. Flour',
	'Saruta Cotton',
	'Scorpion Claw',
	'Scorpion Shell',
	'Semolina',
	'Senroh Sardine',
	'Shall Shell',
	'Sheep Tooth',
	'Silver Ore',
	'Skull Locust',
	'Slime Juice',
	'Snapping Mole',
	'Snap. Secretion',
	'Snap. Tendril',
	'Spider Web',
	'Sunflower Seeds',
	'Swamp Ore',
	'Tarutaru Rice',
	'Three-eyed Fish',
	'Tin Ore',
	'Tiny Goldfish',
	'Titanictus',
	'Titanium Ore',
	'Tree Cuttings',
	'Tulfaire Feather',
	'Turtle Shell',
	'Ulbuconut',
	'Uragnite Shell',
	'Urunday Log',
	'Vanadium Ore',
	'Velkk Mask',
	'Velkk Necklace',
	'Vanilla',
	'Walnut',
	'Walnut Log',
	'Watermelon',
	'Win. Tea Leaves',
	'Wijnruit',
	'Wivre Maul',
	'Woozyshroom',
	'Ulbukan Lobster',
	'Vegetable Seeds',
	'Voay Staff -1',
	'Voay Sword -1',
	'Yagudo Cherry',
	'Yagudo Drink',
	'Yayinbaligi',
	'Yorchete',
	'Zebra Eel',
	'Zinc Ore',
}

return profiles
