-- Add items to existing profiles or create your own to sell groups of items using alias commands
local profiles = {}

profiles['junk'] = S{
    '2Leaf Mandra Bud',
	'Acheron Shield',
	'Acorn',
	'Adamantoise Shell',
	'Adoulinian Kelp',
    'Agaricus',
    'Ahriman Lens',
	'Ahriman Tears',
	'Akaso',
    'Almond',
    'Al Zahbi Sash',
    'Amethyst',
    'Animal Glue',
	'Antican Acid',
	'Antican Pauldron',
	'Antlion Jaw',
	'Apkallu Feather',
    'Aqua Geode',
    'Aquamarine',
    'Arnica Root',
	'Arrowwood Log',
	'Ash Log',
	'Auric Sand',
    'Azuki Bean',
    'Bamboo Stick',
	'Barnacle',
	'Bastore Bream',
	'Bat Fang',
	'Bat Wing',
	'Bay Leaves',
	'Beast Blood',
	'Beehive Chip',
    'Beeswax',
	'Beetle Jaw',
	'Bhefhel Marlin',
	'Bird Blood',
	'Bird Egg',
    'Bird Feather',
	'Bismuth Ore',
    'Bittern',
	'Black Eel',
	'Black Ghost',
	'Black Pepper',
	'Black Prawn',
    'Black Rock',
	'Blk. Tiger Fang',
	'Bloodblotch',
	'Blue Peas',
    'Blue Rock',
	'Bluetail',
	'Bomb Ash',
    'Bugard Skin',
	'Bugard Tusk',
	'Burdock',
    'Butterpear',
	'Bone Chip',
	'Brass Loach',
	'Breeze Geode',
	'Ca Cuong',
	'Cactuar Needle',
	'Cactus Arm',
	'Cactus Stems', 
    'Carap. Powder',
    'Carnation',
	'Carrier Crab Carapace',
    'Cattleya',
    'Chamomile',
	'Chapuli Horn',
	'Chapuli Wing',
	'Chestnut',
	'Chestnut Log',
	'Chestnut Sabots',
	'Chocobo Bedding',
    'Clot Plasma',
    'Cluster Ash',
	'Cobalt Jellyfish',
	'Cockatrice Meat',
	'Cockatrice Skin',
	'Coeurl Meat',
	'Colibri Beak',
	'Cone Calamary',
	'Contortopus',
	'Copper Frog',
	'Copper Ore',
--  'Coral Crest Key', (not vendorable)
    'Coral Fragment',
	'Coral Fungus',
	'Craklaw Pincer',
	'Crab Shell',
	'Crawler Cocoon',
	'Crawler Egg',
    'Crayfish',
	'Crescent Fish',
	'Danceshroom',
	'Dark Bass',
	'Dhalmel Hide',
	'Dst. Nugget',
	'Deathball',
    'Demon Horn',
    'Dhalmel Meat',
    'Diamond Ring',
	'Distilled Water',
	'Divine Log',
--  'Diorite', (not vendorable)
    'Djinn Ash',
	'Dogwood Log',
    'Doll Shard',
    'Dragon Blood',
	'Dragon Bone',
	'Dragon Fruit',
	'Dragonfish',
    'Dst. Bolt Heads',
	'Dwarf Remora',
	'Eastern Ginger',
    'Eft Skin',
	'Eggplant',
	'Elixir Vitae',
	'Elm Log',
    'Elm Staff',
	'Elshimo Newt',
	'El. Pachira Fruit',
	'Emperor Fish',
	'Ether',
	'Faerie Apple',
	'Felicifruit',
	'Fetich Arms',
	'Fetich Head',
	'Fetich Legs',
	'Fetich Torso',
	'Feyweald Log',
    'Fiend Blood',
	'Fish Bones',
    'Fish Scales',
    'Flame Geode',
	'Flax Flower',
	'Flint Stone',
--  'Florid Stone', (not vendorable)
	'Flytrap Leaf',
--  'Fossilized Fang', (not vendorable)
    'Four of Swords',
	'Fresh Marjoram',
	'Fresh Mugwort',
    'Friar\'s Rope',
	'Frost Turnip',
    'Garglle. Shank',
    'Garnet',
	'Gavial Fish',
	'Giant Catfish',
	'Giant Femur',
--  'Giant Scale', (not vendorable)
    'G. Sheep Meat',
	'Giant Stinger',
	'Gigant Squid',
	'Ginger',
    'Gnat Wing',
	'Gold Carp',
    'Gold Orcmask',
	'Gold Ring',
    'Granite',
	'Green Rock',
	'Gregar. Worm',
	'Grimmonite',
	'Grove Cuttings',
	'Guatambu Log',
	'Gugru Tuna',
    'Gules Mittens',
	'Habaneros',
	'Hare Meat',
	'Hecteyes Eye',
    'Hemlock',
    'Hi-Potion +2',
    'Hi-Potion Tank',
    'Holy Basil',
	'Honey',
    'Hydra Meat',
	'Igneous Rock',
	'Imp Wing',
	'Insect Wing',
	'Iron Ore',
    'Iron Sand',
	'Isleracea',
    'Jadeite',
	'Kapor Log',
    'Karugo Clay',
	'Kazham Peppers',
    'Kazham Pineapple',
	'Khroma Ore',
	'King Locust',
	'King Truffle',
	'Kopparnickel Ore',
	'Kukuru Bean',
	'La Theine Cbg.',
	'Lacquer Tree Log',
    'Ladybug Wing',
	'Lamp Marimo',
	'Land Crab Meat',
    'Lanolin',
	'Lauan Log',
	'Leafkin Frond',
    'Leather Gloves',
	'Lesser Chigoe',
    'Light Geode',
    'Light Opal',
	'Little Worm',
    'Living Key',
	'Lizard Blood',
	'Lizard Egg',
	'Lizard Tail',
	'Loc. Elutriator',
    'Lore Sabots',
    'Lucent Steel',
--  'Luminion Chip', (not vendorable)
    'Luminium Ore',
    'Lynx Baghnakhs',
	'Mackerel',
--  'Malevolent Memory', (not vendorable)
    'Manji Shuriken',
    'Manta Skin',
    'Mantid Carapace',
	'Maple Log',
    'Marble Nugget',
	'Marguerite',
   	'Matamata Shell',
	'Matsya',
	'Mercury',
	'Merrow Scale',
	'Meteorite',
	'Mhaura Garlic',
	'Millioncorn',
	'Moko Grass',
    'Moon Ring',
    'Moonring Blade',
	'Moorish Idol',
    'Mujin Stud',
	'Mushroom Locust',
    'Mythril Leaf',
	'Mythril Ore',
	'Napa',
	'Nopales',
	'Oak Log',
    'Onyx',
    'Oversized Fang',
	'Pamamas',
    'Pamtam Kelp',
	'Panopt Tears',
    'Pearl',
	'Pebble',
	'Peiste Skin',
	'Persikos',
    'Petrified Log',
	'Phrygian Ore',
	'Pine Nuts',
	'Pipira',
    'Platinum Leaf',
    'Platinum Ore',
	'Poison Flour',
	'Popoto',
	'Potion',
	'Prize Powder',
	'Puffball',
	'Pugil Scales',
    'Puk Egg',
    'Puk Wing',
	'Pumpkin Pie',
	'Quadav Backplate',
-- 	'Quus', temporarily disabled to feed Zizzaz
    'Ra\'Kaznar Ore',
	'Raaz Hide',
	'Raaz Tusk',
	'Rabbit Hide',
	'Rafflesia Vine',
	'Ram Horn',
	'Raptor Skin',
	'Red Moko Grass',
    'Red Rock',
	'Red Rose',
	'Red Terrapin',
    'Reishi Mushroom',
    'Rock Salt',
	'Rolanberry',
	'Ronfaure Chestnut',
    'Rosewood Log',
    'Royal Jelly',
	'Ruddy Seema',
	'Rusty Bucket',
    'Rusty Leggings',
    'Rusty Pick',
    'Ruszor Meat',
	'Rye Flour',
    'Saffron Blossom',
	'Sage',
    'Salinator',
    'Sanctuary Obi',
	'San d\'Or. Flour',
    'Sardonyx',
	'Saruta Cotton',
    'Scorpion Claw',
    'Scorpion Shell',
    'Sea Zombie',
	'Seashell',
	'Semolina',
	'Senroh Sardine',
    'Shadow Geode',
	'Shall Shell',
	'Shell Shield',
	'Sharug Greens',
    'Sheepskin',
	'Sheep Tooth',
    'Silver Leaf',
	'Silver Ore',
	'Skull Locust',
	'Sleepshroom',
	'Slime Juice',
    'Slug Eye',
    'Smilodon Hide',
	'Snapping Mole',
	'Snap. Secretion',
	'Snap. Tendril',
    'Snoll Arm',
    'Snow Geode',
	'Sobbing Fungus',
    'Soil Geode',
    'Stone II',
    'Sulfur',
	'Sunflower Seeds',
	'Swamp Ore',
	'Tarutaru Rice',
    'Taurus Horn',
	'Thokcha Ingot',
	'Three-eyed Fish',
    'Thunder Geode',
    'Tiger Stole',
	'Tin Ore',
	'Tiny Goldfish',
	'Titanictus',
	'Titanium Ore',
    'Tonberry Coat',
    'Translucent Rock',
	'Tree Cuttings',
	'Tricolored Carp',
	'Trumpet Ring',
	'Tulfaire Feather',
	'Turtle Shell',
    'Twitherym Wing',
	'Ulbuconut',
    'Ulbukan Lobster',
    'Umbril Ooze',
	'Uragnite Shell',
	'Urunday Log',
	'Vanadium Ore',
	'Velkk Mask',
	'Velkk Necklace',
	'Vanilla',
	'Vegetable Seeds',
    'Velkk Mask',
    'Velkk Necklace',
    'Verboshroom',
    'Veydal Wrasse',
    'Vigilance Mantle',
	'Vitriol',
	'Voay Staff -1',
	'Voay Sword -1',
    'Vomp Carrot',
    'Walnut',
    'Wam. Cocoon',
    'Water Lily',
	'Watermelon',
	'White Sand',
	'Win. Tea Leaves',
	'Wijnruit',
	'Wild Pamamas',
    'Winterflower',
    'Wisteria Lumber',
	'Wivre Maul',
    'Wolf Hide',
	'Woozyshroom',
    'Wyrdstrand',
    'Wyvern Scales',
    'Wyvern Skin',
	'Yagudo Cherry',
	'Yagudo Drink',
--  'Yagudo Osode', (not vendorable)
	'Yayinbaligi',
    'Yew Log',
	'Yorchete',
	'Zebra Eel',
    'Zegham Carrot',
	'Zinc Ore',
    'Zircon',
}

return profiles
